### ISSUE TITLE
feat: 리뷰 상세 페이지

### ISSUE THREAD

**Issue by junhyung0806** [prgrms-aibe-devcourse/AIBE2-Project1-Team01#8]
## ✏️ Summary
여행 리뷰 페이지 및 스타일 파일 업로드

<br>

## ✨ Description
- ReviewDetailPage.jsx, ReviewEditPage.jsx: 여행 리뷰 상세, 수정 페이지 개발
- base.css, review.css: 기본 스타일 및 리뷰 전용 스타일 추가
- reviewData.json: 샘플 데이터 추가

<br>

## ✓ Todo
- [x] ReviewDetailPage.jsx 추가
- [x] ReviewEditPage.jsx 추가
- [x] base.css 추가
- [x] review.css 추가
- [x] reviewData.json 추가

<br>

## 🗒️ Note (optional)
없음

<br>

---

# 📄 파일 내용

## 1. ReviewDetailPage.jsx

```jsx
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import reviewDataJson from '../../data/reviewData.json'; // JSON import
import '../../assets/base.css'; // 스타일 import

function ReviewDetailPage() {
  const navigate = useNavigate();
  const [reviewData, setReviewData] = useState(undefined);

  useEffect(() => {
    setReviewData(reviewDataJson);
  }, []);

  const handleRecommend = () => {
    alert('일정 추천 기능은 준비중입니다!');
  };

  const handleClose = () => {
    navigate(-1);
  };

  if (reviewData === undefined) {
    return <div>로딩 중...</div>;
  }

  return (
    <>
      {/* 배경 */}
      <div className="modal-overlay" onClick={handleClose} />

      {/* 모달 */}
      <div className="modal">
        {/* 오른쪽 상단 X버튼 */}
        <button
          onClick={handleClose}
          style={{
            position: 'absolute',
            top: '10px',
            right: '10px',
            background: 'transparent',
            border: 'none',
            fontSize: '20px',
            cursor: 'pointer',
            color: '#999'
          }}
          aria-label="Close modal"
        >
          ✕
        </button>

        {/* 여행지 사진 */}
        <img
          src={reviewData.destination.photoUrl}
          alt="여행지 사진"
          style={{
            borderRadius: '10px',
            width: '100%',
            marginBottom: '10px',
            objectFit: 'contain',
            maxHeight: '250px'
          }}
        />

        {/* 여행지 정보 */}
        <div className="destination-info" style={{ textAlign: 'left' }}>
          <h2>{reviewData.destination.name}</h2>
          <p style={{ whiteSpace: 'pre-line' }}>{reviewData.destination.description}</p>
        </div>

        {/* 별점 */}
        <div className="rating-info" style={{ marginTop: '10px', textAlign: 'center' }}>
          <p>⭐ {reviewData.review.rating}점</p>
        </div>

        {/* 일정 추천 받기 버튼 */}
        <div style={{ marginTop: '20px', textAlign: 'center' }}>
          <button
            className="button recommend-button"
            onClick={handleRecommend}
          >
            일정 추천 받기
          </button>
        </div>

      </div>
    </>
  );
}

export default ReviewDetailPage;
```

## 2. ReviewEditPage.jsx

```jsx
import React, { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import '../../assets/base.css';

function ReviewEditPage() {
  const [photo, setPhoto] = useState(null);
  const [fileName, setFileName] = useState('이미지를 선택하세요');
  const [rating, setRating] = useState(0);
  const [content, setContent] = useState('');
  const [showPopup, setShowPopup] = useState(false);
  const navigate = useNavigate();
  const photoInputRef = useRef(null);

  const handlePhotoChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setFileName(file.name);
      const reader = new FileReader();
      reader.onload = (e) => setPhoto(e.target.result);
      reader.readAsDataURL(file);
    }
  };

  const handleStarClick = (index) => {
    setRating(index);
  };

  const handleSubmit = () => {
    const updatedReview = {
      id: 1,
      destination: {
        name: "제주도",
        description: "제주도는 아름다운 섬입니다.",
        photoUrl: photo
      },
      review: {
        rating: rating,
        content: content
      },
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    };

    localStorage.setItem('reviewData', JSON.stringify(updatedReview));
    navigate('/review/detail');
  };

  const handleDelete = () => {
    setShowPopup(true);
  };

  const confirmDelete = () => {
    localStorage.removeItem('reviewData');
    setShowPopup(false);
    navigate('/');
  };

  const cancelDelete = () => {
    setShowPopup(false);
  };

  const goBack = () => {
    navigate(-1);
  };

  return (
    <div className="review-edit">
      <button className="button back-button" onClick={goBack}>← 뒤로가기</button>

      <div className="photo-upload" style={{ marginTop: '20px' }}>
        {photo ? (
          <img
            src={photo}
            alt="업로드한 사진"
            style={{
              width: '100%',
              height: '250px',
              objectFit: 'contain',
              borderRadius: '10px',
              marginBottom: '10px'
            }}
          />
        ) : (
          <div style={{
            width: '100%',
            height: '250px',
            backgroundColor: '#E0E0E0',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: '10px',
            marginBottom: '10px'
          }}>
            <span>사진</span>
          </div>
        )}

        <div style={{ marginTop: '15px', display: 'flex', alignItems: 'center' }}>
          <label
            htmlFor="photo-input"
            style={{
              padding: '4px 10px',
              backgroundColor: '#E0E0E0',
              border: '1px solid #ccc',
              borderRadius: '5px',
              cursor: 'pointer',
              marginRight: '15px',
              fontSize: '14px'
            }}
          >
            파일 선택
          </label>

          <span style={{ fontSize: '14px', color: '#666' }}>
            {fileName}
          </span>

          <input
            type="file"
            id="photo-input"
            ref={photoInputRef}
            onChange={handlePhotoChange}
            style={{ display: 'none' }}
          />
        </div>
      </div>

      <div className="rating" id="rating" style={{ margin: '10px 0', textAlign: 'center' }}>
        {[1, 2, 3, 4, 5].map((index) => (
          <span
            key={index}
            className="star"
            onClick={() => handleStarClick(index)}
            style={{ fontSize: '24px', cursor: 'pointer' }}
          >
            {index <= rating ? '★' : '☆'}
          </span>
        ))}
      </div>

      <textarea
        id="review-content"
        className="review-content"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        placeholder="리뷰 내용을 입력하세요"
        style={{
          width: '100%',
          height: '120px',
          padding: '10px',
          marginBottom: '20px',
          borderRadius: '10px',
          border: '1px solid #ccc'
        }}
      />

      <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
        <button
          className="button submit-button"
          onClick={handleSubmit}
          style={{ marginRight: '10px' }}
        >
          수정하기
        </button>
        <button className="button delete-button" onClick={handleDelete}>
          삭제
        </button>
      </div>

      {showPopup && (
        <div className="popup">
          <p>정말 삭제하시겠습니까?</p>
          <button className="button submit-button" onClick={confirmDelete}>예</button>
          <button className="button back-button" onClick={cancelDelete}>아니오</button>
        </div>
      )}
    </div>
  );
}

export default ReviewEditPage;
```

## 3. review.css

```css
body {
  margin: 0;
  padding: 0;
  font-family: Arial, sans-serif;
  background-color: #F9FAFB;
}

.App {
  text-align: center;
}

.button {
  padding: 10px 20px;
  margin: 5px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
}

.back-button {
  background-color: #ccc;
}

.submit-button {
  background-color: #4F9DDE;
  color: white;
}

.delete-button {
  background-color: #FF5A5F;
  color: white;
}

.recommend-button {
  background-color: #00C6AE;
  color: white;
}

.star {
  font-size: 30px;
  cursor: pointer;
  color: #FFD700;
}

.popup {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 90%;
  max-width: 400px;
  background: white;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
  padding: 20px;
  text-align: center;
  z-index: 1000;
}
```

## 4. base.css

```css
/* 폰트 및 기본 설정 */
body {
  margin: 0;
  padding: 0;
  font-family: 'Noto Sans KR', sans-serif;
  background-color: #F9FAFB;
  color: #333333;
}

.App {
  text-align: center;
}

/* 버튼 스타일 */
.button {
  padding: 10px 20px;
  margin: 5px;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  font-weight: bold;
  transition: all 0.2s ease;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.button:hover {
  box-shadow: 0 6px 10px rgba(0, 0, 0, 0.15);
  transform: translateY(-2px);
}

.button:active {
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
  transform: translateY(2px);
}

.back-button {
  background-color: #9F9F9F;
  color: white;
}

.submit-button {
  background-color: #4F9DDE;
  color: white;
}

.delete-button {
  background-color: #FF5A5F;
  color: white;
}

.recommend-button {
  background-color: #00C6AE;
  color: white;
}

/* 별점 */
.star {
  font-size: 30px;
  cursor: pointer;
  color: #FFD700;
}

/* 팝업 */
.popup {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 90%;
  max-width: 400px;
  background: white;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.3);
  padding: 20px;
  text-align: center;
  z-index: 1000;
}

/* 텍스트 스타일 */
.large-title {
  font-size: 24px;
  font-weight: 700;
}

.title {
  font-size: 20px;
  font-weight: 500;
}

.sub-title {
  font-size: 18px;
  font-weight: 500;
}

.body-text {
  font-size: 16px;
  font-weight: 500;
}

.caption {
  font-size: 12px;
  font-weight: 500;
}

/* 색상 변수 */
:root {
  --primary-blue: #4F9DDE;
  --light-blue: #C9F0F7;
  --light-green: #D4ED93;
  --yellow: #FFE35C;
  --pale-yellow: #F9FBE7;
  --text-primary: #333333;
  --text-secondary: #9F9F9F;
}

.review-edit {
  max-width: 600px;
  margin: 30px auto;
  padding: 20px;
  background-color: white;
  border-radius: 10px;
}

/* 모달 오버레이 (배경) */
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.5);
  z-index: 999;
}

/* 모달 본체 */
.modal {
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  background: white;
  padding: 40px 20px 20px 20px;
  border-radius: 10px;
  max-width: 500px;
  width: 90%;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);
  z-index: 1000;
}
```

## 5.reviewData.json

```json
{
  "id": 1,
  "destination": {
    "name": "제주도",
    "description": "제주특별자치도(濟州特別自治道, 제주어: 제주특벨ᄌᆞ치도, 영어: Jeju Special Self-Governing Province)는 대한민국의 제주도(濟州島)와 부근 섬들을 관할하는 특별자치도이다. 대한민국에서 가장 큰 섬인 제주도를 비롯하여 마라도, 우도, 추자군도 등을 포함한 유인도 8개, 무인도 55개로 구성되어 있다. 한라산 일대의 아름다운 자연 경관으로 관광업 등 서비스업과 어업이 발달하였고, 제주 화산섬과 용암 동굴은 유네스코 세계 자연 유산에 등재되었다.",
    "photoUrl": "/testimg/제주도.jpg"
  },
  "review": {
    "rating": 5
  },
  "createdAt": "2025-04-28T10:30:00Z",
  "updatedAt": "2025-04-28T12:00:00Z"
}
```
